# Generated by Django 5.2.7 on 2025-12-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_drinkcategory_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
